language: cpp
compiler: g++
before-install:
    - chmod +x build.sh
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
	- g++-4.8
	- libboost-dev
install:
    - CC=gcc-4.8 CXX=g++-4.8
script: ./build.sh
